export const EXAMPLE_RESPONSE = 'EXAMPLE_RESPONSE';
export const EXAMPLE_LOADING = 'EXAMPLE_LOADING';
export const EXAMPLE_ERROR = 'EXAMPLE_ERROR';

//WATCHERS
    export const EXAMPLE_WATCHER = 'EXAMPLE_WATCHER';
//FIM